# Neural Networks

1. Multilayer Perceptron - MNIST Handwritten Numbers
2. Convolutional Neural Networks - 
3. Recurrent Neural Networks - 

In [2]:
import tensorflow as tf
#from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("/tmp/data", one_hot=True)

learning_rate = 0.0005  # how quickly to learn
training_epochs = 25
batch_size = 128

n_classes = 10  # MNIST total classes (0 - 9 digits)
n_samples = mnist.train.num_examples  # (how many images)

n_input = 784  # MNIST data input (img shape is 28x28)

n_hidden_1 = 512  # 1st layer number of neurons
n_hidden_2 = 256  # 2nd layer number of neurons

NameError: name 'input_data' is not defined

In [ ]:
def multilayer_perceptron(x, weights, biases):#, keep_prob):
    '''
    x: Placeholder for data input
    weights: Dictionary of weights
    biases: Dictionary of bias values
    '''
    # First hidden layer with RELU activation
    # X * W + B
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])
    # RELU(X * W + B) = RELU -> f(x) = max(0,x)
    layer_1 = tf.nn.relu(layer_1)
     

    # Second hidden layer
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)

    # Output layer
    out_layer = tf.matmul(layer_2, weights['out']) + biases['out']
    return out_layer

In [92]:
def multilayer_perceptron(x, weights, biases, keep_prob):
    '''
    x: Placeholder for data input
    weights: Dictionary of weights
    biases: Dictionary of bias values
    '''
    # First hidden layer with dropout
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])
    layer_1 = tf.nn.relu(layer_1)
    layer_1 = tf.nn.dropout(layer_1, keep_prob)
    
    # Second hidden layer with dropout
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2) 
    layer_2 = tf.nn.dropout(layer_2, keep_prob)

    # Output layer
    out_layer = tf.sigmoid(tf.matmul(layer_2, weights['out']) + biases['out'])
    return out_layer

In [97]:
weights = {
    'h1':  tf.Variable(tf.random_normal([n_input,    n_hidden_1], stddev=(1/tf.sqrt(float(n_input))))),
    'h2':  tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2], stddev=(1/tf.sqrt(float(n_input))))),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes],  stddev=(1/tf.sqrt(float(n_input)))))
}

biases = {
    'b1':  tf.Variable(tf.random_normal([n_hidden_1])),
    'b2':  tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

x = tf.placeholder('float', [None, n_input])
y = tf.placeholder('float', [None, n_classes])

# add dropout layer
keep_prob = tf.placeholder(tf.float32)

pred = multilayer_perceptron(x, weights, biases, keep_prob)

#cost = tf.reduce_mean(
#    tf.nn.softmax_cross_entropy_with_logits_v2(logits=pred, labels=y))

regularizer_rate = 0.1
cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits_v2(logits=pred, labels=y)) \
        + regularizer_rate*(tf.reduce_sum(tf.square(biases['b1'])) + tf.reduce_sum(tf.square(biases['b2'])))

optimiser = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

sess = tf.InteractiveSession()

init = tf.global_variables_initializer()

sess.run(init)

# 15 loops as we set training_epochs = 15
for epoch in range(training_epochs):
    # Cost
    avg_cost = 0.0
    total_batch = int(n_samples/batch_size)
    for i in range(total_batch):
        # Grab the next batch of training data and labels
        batch_x, batch_y = mnist.train.next_batch(batch_size)
        # Feed dictionary for optimization and loss value
        # Returns a tuple, but we only need 'c' the cost
        # So we set an underscore as a "throwaway"
        # Feed a value < 1.0 to keep prob during training
        _, c = sess.run([optimiser, cost], feed_dict={
                        x: batch_x, y: batch_y, keep_prob: 1})
        avg_cost += c/total_batch
    print("Epoch {}: cost={:.4f}".format(epoch+1, avg_cost))
print("Model has completed {} Epochs of training".format(training_epochs))


correct_pred = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))  # checks if x==y?
correct_pred = tf.cast(correct_pred, 'float')
accuracy = tf.reduce_mean(correct_pred)
# feed a value of 1.0 to keep prob
accuracy.eval({x: mnist.test.images, y: mnist.test.labels, keep_prob: 1.0})

Epoch 1: cost=63.0963
Epoch 2: cost=44.8840
Epoch 3: cost=32.0865
Epoch 4: cost=22.9439
Epoch 5: cost=16.3933
Epoch 6: cost=11.7135
Epoch 7: cost=8.3958
Epoch 8: cost=6.0726
Epoch 9: cost=4.4707
Epoch 10: cost=3.3857
Epoch 11: cost=2.6641
Epoch 12: cost=2.1937
Epoch 13: cost=1.8938
Epoch 14: cost=1.7068
Epoch 15: cost=1.5946
Epoch 16: cost=1.5302
Epoch 17: cost=1.4953
Epoch 18: cost=1.4778
Epoch 19: cost=1.4697
Epoch 20: cost=1.4670
Epoch 21: cost=1.4659
Epoch 22: cost=1.4652
Epoch 23: cost=1.4650
Epoch 24: cost=1.4651
Epoch 25: cost=1.4650
Model has completed 25 Epochs of training


0.9815

In [99]:
import numpy as np
import sklearn as sk

#metrics
y_p = tf.argmax(pred, 1)
val_accuracy, y_pred = sess.run([accuracy, y_p], feed_dict={x: mnist.test.images, y: mnist.test.labels, keep_prob: 1.0})

print("validation accuracy:", val_accuracy)
y_true = np.argmax(mnist.test.labels,1)
print("Precision", sk.metrics.precision_score(y_true, y_pred, average='micro'))
print("Recall", sk.metrics.recall_score(y_true, y_pred, average='micro'))
print("f1_score", sk.metrics.f1_score(y_true, y_pred, average='micro'))
print("confusion_matrix")
print(sk.metrics.confusion_matrix(y_true, y_pred))

validation accuracy: 0.9815
Precision 0.9815
Recall 0.9815
f1_score 0.9815
confusion_matrix
[[ 975    1    0    0    0    0    2    1    1    0]
 [   1 1124    3    0    0    1    4    0    2    0]
 [   3    2 1012    1    2    0    1    6    4    1]
 [   1    0    6  990    0    2    1    4    3    3]
 [   0    0    2    0  957    0    6    2    1   14]
 [   3    0    0    5    1  875    3    1    2    2]
 [   4    2    1    1    2    2  946    0    0    0]
 [   0    5    9    0    0    0    0 1006    3    5]
 [   4    0    3    3    5    2    4    5  944    4]
 [   3    2    0    3    4    2    2    6    1  986]]
